Repository ProvableHQ/sdk, pull requests merged in 2023-02, with the labels that each got.

#457 Update the license headers
  .resources/license_header
  build.rs
  cli/commands/account.rs
  cli/commands/build.rs
  cli/commands/clean.rs
  cli/commands/deploy.rs
  cli/commands/mod.rs
  cli/commands/new.rs
  cli/commands/node.rs
  cli/commands/run.rs
  cli/commands/update.rs
  cli/errors.rs
  cli/helpers/ledger.rs
  cli/helpers/mod.rs
  cli/helpers/updater.rs
  cli/lib.rs
  cli/main.rs
  rust/account/benches/account.rs
  rust/account/src/lib.rs
  rust/account/src/tests.rs
  wasm/src/account/address.rs
  wasm/src/account/mod.rs
  wasm/src/account/private_key.rs
  wasm/src/account/signature.rs
  wasm/src/account/view_key.rs
  wasm/src/lib.rs
  wasm/src/record/mod.rs
  wasm/src/record/record_ciphertext.rs
  wasm/src/record/record_plaintext.rs
Labels: documentation

#470 Unit testing for typescript SDK in CI
  .circleci/config.yml
  sdk/jestconfig.json
  sdk/package.json
  sdk/src/account.d.ts
  sdk/src/account.js
  sdk/src/account.js.map
  sdk/src/account.ts
  sdk/src/node_connection.ts
  sdk/tests/account.test.ts
  sdk/tsconfig.json
Labels: CI/Test Coverage

#473 Add test coverage for js objects auto-generated by wasm
  sdk/tests/account-data.ts
  sdk/tests/account.test.ts
  sdk/tests/wasm.test.ts
Labels: CI/Test Coverage

#467 [Feature] Add serial number function to aleo wasm
  wasm/src/account/private_key.rs
  wasm/src/record/record_plaintext.rs
  wasm/src/types.rs
Labels: enhancement

#476 Create integation test script for Aleo CLI
  .circleci/aleo-new.sh
  .circleci/config.yml
  foo/README.md
  foo/main.aleo
  foo/program.json
  sdk/src/account.d.ts
  sdk/src/account.js
  sdk/src/account.js.map
Labels: CI/Test Coverage
